# ══════════════════════════════════════════════
#  Cold — Frost (Winter Blue)
# ══════════════════════════════════════════════
CU="$HOME/.config/theming/color-util.py"
c() { python3 "$CU" "$@"; }

# === Main Colors ===
export THEME_COLOR_BG_COLOR="#151B23"
export THEME_COLOR_FG_COLOR="#C0CEDB"
export THEME_COLOR_FG_DIMMED="#6B8299"
export THEME_COLOR_ACCENT="#7ABAFF"
export THEME_COLOR_BORDER="rgba(122, 186, 255, 0.8)"

# === ANSI Palette ===
export THEME_COLOR_TERMINAL_COLOR_0="#2C3847"
export THEME_COLOR_TERMINAL_COLOR_1="#E06C75"
export THEME_COLOR_TERMINAL_COLOR_2="#88C0A0"
export THEME_COLOR_TERMINAL_COLOR_3="#D4B97D"
export THEME_COLOR_TERMINAL_COLOR_4="#7ABAFF"
export THEME_COLOR_TERMINAL_COLOR_5="#B48EAD"
export THEME_COLOR_TERMINAL_COLOR_6="#8FBCDB"
export THEME_COLOR_TERMINAL_COLOR_7="#C0CEDB"
export THEME_COLOR_TERMINAL_COLOR_8="#3D4F63"
export THEME_COLOR_TERMINAL_COLOR_9="#D45B65"
export THEME_COLOR_TERMINAL_COLOR_10="#9FD4B0"
export THEME_COLOR_TERMINAL_COLOR_11="#E5CC8E"
export THEME_COLOR_TERMINAL_COLOR_12="#5DA3E6"
export THEME_COLOR_TERMINAL_COLOR_13="#C99FBD"
export THEME_COLOR_TERMINAL_COLOR_14="#A3D0EB"
export THEME_COLOR_TERMINAL_COLOR_15="#DAE4ED"

# === Computed: Terminal UI ===
export THEME_COLOR_TERMINAL_SELECTION_BG_COLOR=$(c mix "$THEME_COLOR_ACCENT" "$THEME_COLOR_BG_COLOR" 30)
export THEME_COLOR_TERMINAL_SELECTION_FG_COLOR="$THEME_COLOR_FG_COLOR"
export THEME_COLOR_TERMINAL_CURSOR_COLOR="$THEME_COLOR_FG_COLOR"
export THEME_COLOR_TERMINAL_CURSOR_TEXT_COLOR="$THEME_COLOR_BG_COLOR"
export THEME_COLOR_TERMINAL_URL_COLOR="$THEME_COLOR_ACCENT"
export THEME_COLOR_TERMINAL_ACTIVE_TAB_FOREGROUND="$THEME_COLOR_BG_COLOR"
export THEME_COLOR_TERMINAL_ACTIVE_TAB_BACKGROUND="$THEME_COLOR_ACCENT"
export THEME_COLOR_TERMINAL_INACTIVE_TAB_FOREGROUND="$THEME_COLOR_FG_DIMMED"
export THEME_COLOR_TERMINAL_INACTIVE_TAB_BACKGROUND=$(c lighten "$THEME_COLOR_BG_COLOR" 5)

# === Computed: Status Bar ===
export THEME_COLOR_SELECTED_WORKSPACE="$THEME_COLOR_ACCENT"
export THEME_COLOR_ACTIVE_WORKSPACE=$(c lighten "$THEME_COLOR_BG_COLOR" 15)
export THEME_COLOR_INACTIVE_WORKSPACE=$(c lighten "$THEME_COLOR_BG_COLOR" 4)

# === Computed: Vesktop ===
export THEME_COLOR_VESKTOP_BG_DARKER=$(c darken "$THEME_COLOR_BG_COLOR" 3)
export THEME_COLOR_VESKTOP_BG_MAIN=$(c lighten "$THEME_COLOR_BG_COLOR" 2)
export THEME_COLOR_VESKTOP_BG_BUTTON=$(c lighten "$THEME_COLOR_BG_COLOR" 1)
export THEME_COLOR_VESKTOP_BG_LIGHTER=$(c lighten "$THEME_COLOR_BG_COLOR" 6)
export THEME_COLOR_VESKTOP_TEXT_BRIGHT=$(c lighten "$THEME_COLOR_FG_COLOR" 25)
export THEME_COLOR_VESKTOP_TEXT_MID=$(c mix "$THEME_COLOR_FG_COLOR" "$THEME_COLOR_FG_DIMMED" 50)
export THEME_COLOR_VESKTOP_GRAY_DARK=$(c darken "$THEME_COLOR_FG_DIMMED" 12)

# === Computed: Swaync ===
export THEME_COLOR_SWAYNC_BG=$(c darken "$THEME_COLOR_BG_COLOR" 1)
export THEME_COLOR_SWAYNC_BG_ELEVATED=$(c lighten "$THEME_COLOR_BG_COLOR" 6)
export THEME_COLOR_SWAYNC_BG_HOVER=$(c lighten "$THEME_COLOR_BG_COLOR" 12)
export THEME_COLOR_SWAYNC_BG_ACTIVE=$(c lighten "$THEME_COLOR_BG_COLOR" 16)
export THEME_COLOR_SWAYNC_BG_PRESSED=$(c lighten "$THEME_COLOR_BG_COLOR" 22)
export THEME_COLOR_SWAYNC_TEXT_BRIGHT=$(c lighten "$THEME_COLOR_FG_COLOR" 15)
export THEME_COLOR_SWAYNC_SLIDER=$(c mix "$THEME_COLOR_FG_COLOR" "$THEME_COLOR_FG_DIMMED" 40)

# === Computed: Rofi ===
export THEME_COLOR_ROFI_BG="$THEME_COLOR_BG_COLOR"
export THEME_COLOR_ROFI_BG_ALT=$(c lighten "$THEME_COLOR_BG_COLOR" 6)
export THEME_COLOR_ROFI_FG="$THEME_COLOR_FG_COLOR"
export THEME_COLOR_ROFI_SELECTED="$THEME_COLOR_ACCENT"
export THEME_COLOR_ROFI_ACTIVE=$(c lighten "$THEME_COLOR_BG_COLOR" 8)
export THEME_COLOR_ROFI_URGENT="$THEME_COLOR_FG_DIMMED"

# === Computed: Cava ===
export THEME_COLOR_CAVA_GRADIENT_1="$THEME_COLOR_TERMINAL_COLOR_6"
export THEME_COLOR_CAVA_GRADIENT_2=$(c mix "$THEME_COLOR_TERMINAL_COLOR_6" "$THEME_COLOR_TERMINAL_COLOR_4" 30)
export THEME_COLOR_CAVA_GRADIENT_3=$(c mix "$THEME_COLOR_TERMINAL_COLOR_6" "$THEME_COLOR_TERMINAL_COLOR_4" 60)
export THEME_COLOR_CAVA_GRADIENT_4="$THEME_COLOR_TERMINAL_COLOR_4"
export THEME_COLOR_CAVA_GRADIENT_5=$(c mix "$THEME_COLOR_TERMINAL_COLOR_4" "$THEME_COLOR_TERMINAL_COLOR_5" 50)
export THEME_COLOR_CAVA_GRADIENT_6="$THEME_COLOR_TERMINAL_COLOR_5"
export THEME_COLOR_CAVA_GRADIENT_7=$(c mix "$THEME_COLOR_TERMINAL_COLOR_5" "$THEME_COLOR_TERMINAL_COLOR_1" 50)
export THEME_COLOR_CAVA_GRADIENT_8="$THEME_COLOR_TERMINAL_COLOR_1"

# === Computed: Hyprland (rgba without #, with alpha suffix) ===
export THEME_COLOR_HYPR_ACTIVE_BORDER_1="$(c strip "$THEME_COLOR_ACCENT")cc"
export THEME_COLOR_HYPR_ACTIVE_BORDER_2="$(c strip $(c darken "$THEME_COLOR_ACCENT" 30))ff"
export THEME_COLOR_HYPR_INACTIVE_BORDER_1="$(c strip $(c lighten "$THEME_COLOR_BG_COLOR" 10))ff"
export THEME_COLOR_HYPR_INACTIVE_BORDER_2="$(c strip $(c lighten "$THEME_COLOR_BG_COLOR" 10))55"
export THEME_COLOR_HYPR_SHADOW="$(c strip "$THEME_COLOR_BG_COLOR")ee"
